version: '3.8'

services:
  a365ss-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: a365ss_react_app
    ports:
      - "8084:80" # Maps port 8084 on the server to port 80 in the container
    restart: unless-stopped
