services:
  - type: web
    name: hr-requests-client
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_APP_ENV
        value: prod
    routes:
      - type: rewrite
        source: /chat-new/*
        destination: https://iam.omnicloudapi.com/api/chat-new/*
      - type: rewrite
        source: /chat/*
        destination: https://iam.omnicloudapi.com/api/chat/*
      - type: rewrite
        source: /*
        destination: /index.html
